/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sarltokyo_flvdownloadservice_FlvDownloadService */

#ifndef _Included_com_sarltokyo_flvdownloadservice_FlvDownloadService
#define _Included_com_sarltokyo_flvdownloadservice_FlvDownloadService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sarltokyo_flvdownloadservice_FlvDownloadService
 * Method:    flvstreamerw
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sarltokyo_flvdownloadservice_FlvDownloadService_flvstreamerw
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
